mod capability;mod environment;mod jobs;mod managed_java;mod network;mod sandbox;
use agmp_native_protocol::*;use anyhow::Result;use capability::*;use jobs::JobManager;use serde_json::Value;use std::{fs,path::PathBuf};
#[derive(Clone)]pub struct NativeRuntime{workspace:PathBuf,managed:PathBuf,capabilities:CapabilityManager,jobs:JobManager}
impl NativeRuntime{pub fn new(workspace:PathBuf,managed:PathBuf)->Result<Self>{fs::create_dir_all(&workspace)?;fs::create_dir_all(&managed)?;let workspace=workspace.canonicalize()?;let managed=managed.canonicalize()?;Ok(Self{jobs:JobManager::new(workspace.clone()),workspace,managed,capabilities:CapabilityManager::new()})}pub fn status(&self)->RuntimeStatus{RuntimeStatus{name:"AGMP Native Runtime".into(),version:"0.4.0".into(),protocol:PROTOCOL_VERSION.into(),ready:true,capabilities:vec!["capability.lease.v1".into(),"filesystem.root-confined".into(),"filesystem.write.capability".into(),"process.job.capability".into(),"environment.java-managed".into(),"network.download.verified".into(),"minecraft.status-ping".into()]}}pub fn issue(&self,r:CapabilityIssueRequest)->Result<CapabilityLease>{self.capabilities.issue(r)}
 pub fn list(&self,path:&str)->Result<Value>{let p=sandbox::resolve(&self.workspace,path,true)?;let mut out=Vec::new();for e in fs::read_dir(p)?{let e=e?;let m=e.metadata()?;out.push(serde_json::json!({"name":e.file_name().to_string_lossy(),"path":e.path().to_string_lossy(),"directory":m.is_dir(),"bytes":m.len()}))}Ok(Value::Array(out))}
 pub fn read_text(&self,path:&str)->Result<Value>{let p=sandbox::resolve(&self.workspace,path,true)?;Ok(serde_json::json!({"content":fs::read_to_string(p)?}))}
 pub fn create_dir(&self,r:FileCreateDirRequest)->Result<()> {let payload=serde_json::json!({"path":r.path});self.capabilities.consume(&r.capability_lease_id,FS_MKDIR,&r.run_id,&r.tool,&payload)?;let p=sandbox::resolve(&self.workspace,payload["path"].as_str().unwrap(),false)?;fs::create_dir_all(p)?;Ok(())}
 pub fn write_text(&self,r:FileWriteTextRequest)->Result<()> {let payload=serde_json::json!({"path":r.path,"content":r.content});self.capabilities.consume(&r.capability_lease_id,FS_WRITE,&r.run_id,&r.tool,&payload)?;let p=sandbox::resolve(&self.workspace,payload["path"].as_str().unwrap(),false)?;if let Some(parent)=p.parent(){fs::create_dir_all(parent)?}fs::write(p,payload["content"].as_str().unwrap())?;Ok(())}
 pub fn start_job(&self,r:JobStartRequest)->Result<JobSnapshot>{let payload=serde_json::json!({"sessionId":r.session_id,"executable":r.executable,"arguments":r.arguments,"cwd":r.cwd,"maxOutputBytes":r.max_output_bytes});self.capabilities.consume(&r.capability_lease_id,PROCESS_START,&r.run_id,&r.tool,&payload)?;self.jobs.start(r)}pub fn job_get(&self,id:&str)->Result<JobSnapshot>{self.jobs.get(id)}pub fn job_output(&self,id:&str,after:u64,limit:usize)->Result<Value>{self.jobs.output(id,after,limit)}
 pub fn java_inspect(&self)->JavaRuntimeInfo{environment::inspect_java(&self.managed)}pub fn java_ensure(&self,r:ManagedJavaRequest)->Result<JavaRuntimeInfo>{let payload=serde_json::json!({"major":r.major});self.capabilities.consume(&r.capability_lease_id,JAVA_ENSURE,&r.run_id,&r.tool,&payload)?;managed_java::ensure(&self.managed,r.major)}
 pub fn port_available(&self,host:&str,port:u16)->Value{serde_json::json!({"host":host,"port":port,"available":network::port_available(host,port)})}
 pub fn download(&self,r:DownloadRequest)->Result<Value>{let payload=serde_json::json!({"url":r.url,"path":r.path,"hash":r.hash,"hashType":r.hash_type,"maxBytes":r.max_bytes});self.capabilities.consume(&r.capability_lease_id,DOWNLOAD,&r.run_id,&r.tool,&payload)?;network::download_verified(&self.workspace,payload["url"].as_str().unwrap(),payload["path"].as_str().unwrap(),payload["hash"].as_str().unwrap(),payload["hashType"].as_str().unwrap(),payload["maxBytes"].as_u64().unwrap_or(0))}
 pub fn mc_ping(&self,host:&str,port:u16,timeout:u64)->Result<MinecraftPingResult>{network::minecraft_ping(host,port,timeout)}}
