import type { AgentMessage, JsonObject, ModelTurn, ToolCall, ToolSpec } from '../../protocol/src/index.ts'
import type { ModelGenerateInput, ModelProvider } from './index.ts'
const ZERO = { inputTokens: 0, outputTokens: 0, reasoningTokens: 0, totalTokens: 0 }
function toolDefs(tools: ToolSpec[]) { return tools.map(tool => ({ type: 'function', name: tool.name, description: tool.description, parameters: tool.inputSchema })) }
function openaiInput(messages: AgentMessage[]): any[] { return messages.flatMap<any>(message => { if (message.role === 'tool') return [{ type: 'function_call_output', call_id: message.toolCallId ?? '', output: message.content }]; if (message.role === 'assistant' && message.toolCalls?.length) return message.toolCalls.map(call => ({ type: 'function_call', call_id: call.id, name: call.name, arguments: JSON.stringify(call.arguments) })); return [{ role: message.role, content: message.content }] }) }
function authHeaders(apiKey: string, extra: Record<string,string> = {}) { return { 'content-type': 'application/json', accept: 'application/json', authorization: `Bearer ${apiKey}`, ...extra } }
async function jsonResponse(response: Response) { const text = await response.text(); if (!response.ok) throw new Error(`Model HTTP ${response.status}: ${text.slice(0, 1200)}`); try { return JSON.parse(text) as any } catch { throw new Error('Model returned invalid JSON') } }
export class OpenAIResponsesProvider implements ModelProvider {
  constructor(public readonly id: string, public readonly model: string, private readonly baseUrl: string, private readonly apiKey: string) {}
  readonly protocol = 'openai-responses'
  async generate(input: ModelGenerateInput): Promise<ModelTurn> {
    const started = Date.now(); const response = await fetch(`${this.baseUrl.replace(/\/$/,'')}/responses`, { method: 'POST', headers: authHeaders(this.apiKey), signal: input.signal, body: JSON.stringify({ model: this.model, instructions: input.system, input: openaiInput(input.messages), tools: toolDefs(input.tools), tool_choice: 'auto' }) }); const body = await jsonResponse(response)
    const toolCalls: ToolCall[] = []; let text = ''
    for (const item of body.output ?? []) { if (item.type === 'function_call') { let args: JsonObject = {}; try { args = JSON.parse(item.arguments || '{}') as JsonObject } catch {} toolCalls.push({ id: String(item.call_id || item.id || `call-${toolCalls.length+1}`), name: String(item.name || ''), arguments: args }) } else if (item.type === 'message') for (const content of item.content ?? []) if (content.type === 'output_text') text += String(content.text ?? '') }
    const usage = body.usage ? { inputTokens: Number(body.usage.input_tokens ?? 0), outputTokens: Number(body.usage.output_tokens ?? 0), reasoningTokens: Number(body.usage.output_tokens_details?.reasoning_tokens ?? 0), totalTokens: Number(body.usage.total_tokens ?? 0) } : { ...ZERO }
    return { text, toolCalls, usage, provider: this.id, model: this.model, protocol: this.protocol, latencyMs: Date.now()-started } as ModelTurn & { latencyMs:number }
  }
}
function chatMessages(system: string, messages: AgentMessage[]) { const out:any[]=[{role:'system',content:system}]; for(const m of messages){ if(m.role==='tool') out.push({role:'tool',tool_call_id:m.toolCallId,content:m.content}); else if(m.role==='assistant' && m.toolCalls?.length) out.push({role:'assistant',content:m.content||null,tool_calls:m.toolCalls.map(c=>({id:c.id,type:'function',function:{name:c.name,arguments:JSON.stringify(c.arguments)}}))}); else out.push({role:m.role,content:m.content}); } return out }
export class OpenAIChatProvider implements ModelProvider {
  constructor(public readonly id:string, public readonly model:string, private readonly baseUrl:string, private readonly apiKey:string){}
  readonly protocol='openai-compatible'
  async generate(input:ModelGenerateInput):Promise<ModelTurn>{ const response=await fetch(`${this.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:authHeaders(this.apiKey),signal:input.signal,body:JSON.stringify({model:this.model,messages:chatMessages(input.system,input.messages),tools:input.tools.map(t=>({type:'function',function:{name:t.name,description:t.description,parameters:t.inputSchema}})),tool_choice:'auto'})}); const body=await jsonResponse(response); const choice=body.choices?.[0]?.message ?? {}; const calls:ToolCall[]=(choice.tool_calls??[]).map((c:any)=>{let args={};try{args=JSON.parse(c.function?.arguments||'{}')}catch{}return{id:String(c.id||''),name:String(c.function?.name||''),arguments:args}}); const u=body.usage??{}; return{text:String(choice.content??''),toolCalls:calls,usage:{inputTokens:Number(u.prompt_tokens??0),outputTokens:Number(u.completion_tokens??0),reasoningTokens:Number(u.completion_tokens_details?.reasoning_tokens??0),totalTokens:Number(u.total_tokens??0)},provider:this.id,model:this.model,protocol:this.protocol} }
}
export class AnthropicProvider implements ModelProvider {
  constructor(public readonly id:string, public readonly model:string, private readonly baseUrl:string, private readonly apiKey:string){}
  readonly protocol='anthropic'
  async generate(input:ModelGenerateInput):Promise<ModelTurn>{ const messages:any[]=[]; for(const m of input.messages){ if(m.role==='system')continue; if(m.role==='tool') messages.push({role:'user',content:[{type:'tool_result',tool_use_id:m.toolCallId,content:m.content}]}); else if(m.role==='assistant'&&m.toolCalls?.length) messages.push({role:'assistant',content:[...(m.content?[{type:'text',text:m.content}]:[]),...m.toolCalls.map(c=>({type:'tool_use',id:c.id,name:c.name,input:c.arguments}))]}); else messages.push({role:m.role==='assistant'?'assistant':'user',content:m.content}); }
    const response=await fetch(`${this.baseUrl.replace(/\/$/,'')}/v1/messages`,{method:'POST',headers:{'content-type':'application/json','x-api-key':this.apiKey,'anthropic-version':'2023-06-01'},signal:input.signal,body:JSON.stringify({model:this.model,max_tokens:4096,system:input.system,messages,tools:input.tools.map(t=>({name:t.name,description:t.description,input_schema:t.inputSchema}))})}); const body=await jsonResponse(response); const calls:ToolCall[]=[]; let text=''; for(const item of body.content??[]){ if(item.type==='text')text+=String(item.text??''); else if(item.type==='tool_use')calls.push({id:String(item.id),name:String(item.name),arguments:(item.input??{}) as JsonObject}); } const u=body.usage??{}; return{text,toolCalls:calls,usage:{inputTokens:Number(u.input_tokens??0),outputTokens:Number(u.output_tokens??0),reasoningTokens:0,totalTokens:Number(u.input_tokens??0)+Number(u.output_tokens??0)},provider:this.id,model:this.model,protocol:this.protocol} }
}
export class GeminiProvider implements ModelProvider {
  constructor(public readonly id:string, public readonly model:string, private readonly baseUrl:string, private readonly apiKey:string){}
  readonly protocol='gemini'
  async generate(input:ModelGenerateInput):Promise<ModelTurn>{ const contents:any[]=[]; for(const m of input.messages){ if(m.role==='tool') contents.push({role:'user',parts:[{functionResponse:{name:m.name??'',response:{result:m.content}}}]}); else if(m.role==='assistant'&&m.toolCalls?.length) contents.push({role:'model',parts:m.toolCalls.map(c=>({functionCall:{name:c.name,args:c.arguments}}))}); else contents.push({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}); } const url=`${this.baseUrl.replace(/\/$/,'')}/v1beta/models/${encodeURIComponent(this.model)}:generateContent?key=${encodeURIComponent(this.apiKey)}`; const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},signal:input.signal,body:JSON.stringify({systemInstruction:{parts:[{text:input.system}]},contents,tools:[{functionDeclarations:input.tools.map(t=>({name:t.name,description:t.description,parameters:t.inputSchema}))}]})}); const body=await jsonResponse(response); const parts=body.candidates?.[0]?.content?.parts??[]; const calls:ToolCall[]=[]; let text=''; for(const part of parts){ if(part.text)text+=String(part.text); if(part.functionCall)calls.push({id:`gemini-${calls.length+1}`,name:String(part.functionCall.name),arguments:(part.functionCall.args??{}) as JsonObject}); } const u=body.usageMetadata??{}; return{text,toolCalls:calls,usage:{inputTokens:Number(u.promptTokenCount??0),outputTokens:Number(u.candidatesTokenCount??0),reasoningTokens:Number(u.thoughtsTokenCount??0),totalTokens:Number(u.totalTokenCount??0)},provider:this.id,model:this.model,protocol:this.protocol} }
}
