import { randomUUID } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { ModelProvider } from './index.ts'
import { AnthropicProvider, GeminiProvider, OpenAIChatProvider, OpenAIResponsesProvider } from './providers.ts'
export type ModelProtocol='openai-responses'|'openai-compatible'|'deepseek'|'anthropic'|'gemini'|'codex-cli'|string
export interface ModelCapabilities { tools:boolean; vision:boolean; reasoning:boolean; streaming:boolean; subscription?:boolean }
export interface ModelProfile { id:string; name:string; provider:string; protocol:ModelProtocol; model:string; baseUrl:string; authMode:'api-key'|'subscription'; capabilities:ModelCapabilities; verifiedAt?:string; verifyMessage?:string }
export interface SaveModelInput { id?:string; name:string; provider:string; protocol:ModelProtocol; model:string; baseUrl?:string; authMode?:'api-key'|'subscription'; apiKey?:string; capabilities?:Partial<ModelCapabilities> }
export interface ModelConnectionInput extends SaveModelInput {}
type Secrets=Record<string,string>
const defaults:Record<string,string>={ 'openai-responses':'https://api.openai.com/v1','openai-compatible':'https://api.openai.com/v1',deepseek:'https://api.deepseek.com/v1',anthropic:'https://api.anthropic.com',gemini:'https://generativelanguage.googleapis.com' }
export class ModelProfileStore {
  #root:string; #profilesFile:string; #secretsFile:string; #stateFile:string
  constructor(root:string){this.#root=path.join(root,'models');this.#profilesFile=path.join(this.#root,'profiles.json');this.#secretsFile=path.join(this.#root,'secrets.json');this.#stateFile=path.join(this.#root,'state.json')}
  async catalog(){const profiles=await this.#profiles();const state=await this.#state();const active=profiles.find(p=>p.id===state.defaultBrainId);const ready=Boolean(active?.verifiedAt);return{presets:[{id:'openai',name:'OpenAI',protocol:'openai-responses'},{id:'anthropic',name:'Anthropic',protocol:'anthropic'},{id:'gemini',name:'Google Gemini',protocol:'gemini'},{id:'deepseek',name:'DeepSeek',protocol:'deepseek'},{id:'codex',name:'OpenAI Codex CLI Subscription',protocol:'codex-cli'}],profiles,defaultBrainId:state.defaultBrainId??'',brainReady:ready,message:ready?`${active!.provider} · ${active!.model}`:'请先验证并选择一个厂商模型作为 XiaoYu 默认大脑'} }
  async save(input:SaveModelInput):Promise<ModelProfile>{const profiles=await this.#profiles();const id=input.id?.trim()||`model_${randomUUID()}`;const existing=profiles.find(p=>p.id===id);const normalized=this.#normalize(input,id);if(existing&&(existing.provider!==normalized.provider||existing.protocol!==normalized.protocol||existing.model!==normalized.model||existing.baseUrl!==normalized.baseUrl||Boolean(input.apiKey))){normalized.verifiedAt=undefined;normalized.verifyMessage=undefined}else if(existing){normalized.verifiedAt=existing.verifiedAt;normalized.verifyMessage=existing.verifyMessage}const next=profiles.filter(p=>p.id!==id);next.push(normalized);await this.#write(this.#profilesFile,next);if(input.apiKey?.trim()){const secrets=await this.#secrets();secrets[id]=input.apiKey.trim();await this.#write(this.#secretsFile,secrets)}return structuredClone(normalized)}
  async testConnection(input:ModelConnectionInput){const profile=this.#normalize(input,input.id?.trim()||`probe_${randomUUID()}`);if(profile.protocol==='codex-cli')return{ok:false,message:'Codex CLI 套餐适配器已进入 0.4 架构，但 Native CLI 登录/执行桥将在下一阶段启用。',provider:profile.provider,model:profile.model,protocol:profile.protocol};const key=input.apiKey?.trim()||((await this.#secrets())[profile.id]??'');if(!key)throw new Error('API Key 未配置');const provider=this.#provider(profile,key);const result=await provider.generate({system:'You are a connection probe. You must call agmp_probe exactly once.',messages:[{role:'user',content:'Call agmp_probe with {"ok":true}.'}],tools:[{name:'agmp_probe',description:'AGMP model tool capability probe',risk:'read',source:'probe',inputSchema:{type:'object',properties:{ok:{type:'boolean'}},required:['ok'],additionalProperties:false}}]});const toolOk=result.toolCalls.some(call=>call.name==='agmp_probe');if(!toolOk)throw new Error('模型生成可用，但没有完成 Tool Call Probe；不能作为 XiaoYu Agent 默认大脑');if(input.id){const profiles=await this.#profiles();const item=profiles.find(p=>p.id===input.id);if(item){item.verifiedAt=new Date().toISOString();item.verifyMessage='Generation + Tool Call Probe PASS';await this.#write(this.#profilesFile,profiles)}}return{ok:true,message:'真实 Generation + Tool Call Probe PASS',provider:profile.provider,model:profile.model,protocol:profile.protocol,capabilities:profile.capabilities}}
  async setDefault(id:string){const profiles=await this.#profiles();const profile=profiles.find(p=>p.id===id);if(!profile)throw new Error('模型配置不存在');if(!profile.verifiedAt)throw new Error('该模型尚未通过真实 Generation + Tool Call Probe');await this.#write(this.#stateFile,{defaultBrainId:id});return this.catalog()}
  async remove(id:string){const profiles=(await this.#profiles()).filter(p=>p.id!==id);await this.#write(this.#profilesFile,profiles);const secrets=await this.#secrets();delete secrets[id];await this.#write(this.#secretsFile,secrets);const state=await this.#state();if(state.defaultBrainId===id)await this.#write(this.#stateFile,{})}
  async defaultProvider():Promise<ModelProvider>{const catalog=await this.catalog();const profile=catalog.profiles.find(p=>p.id===catalog.defaultBrainId);if(!profile||!catalog.brainReady)throw new Error(catalog.message);if(profile.protocol==='codex-cli')throw new Error('Codex CLI subscription provider is configured but Native subscription adapter is not enabled yet');const key=(await this.#secrets())[profile.id];if(!key)throw new Error('默认模型密钥缺失');return this.#provider(profile,key)}
  #provider(p:ModelProfile,key:string):ModelProvider{if(p.protocol==='openai-responses')return new OpenAIResponsesProvider(p.provider,p.model,p.baseUrl,key);if(p.protocol==='anthropic')return new AnthropicProvider(p.provider,p.model,p.baseUrl,key);if(p.protocol==='gemini')return new GeminiProvider(p.provider,p.model,p.baseUrl,key);return new OpenAIChatProvider(p.provider,p.model,p.baseUrl,key)}
  #normalize(input:SaveModelInput,id:string):ModelProfile{return{id,name:input.name.trim()||input.model.trim(),provider:input.provider.trim()||input.protocol,protocol:input.protocol,model:input.model.trim(),baseUrl:(input.baseUrl?.trim()||defaults[input.protocol]||'').replace(/\/$/,''),authMode:input.authMode??(input.protocol==='codex-cli'?'subscription':'api-key'),capabilities:{tools:input.capabilities?.tools??true,vision:input.capabilities?.vision??false,reasoning:input.capabilities?.reasoning??true,streaming:input.capabilities?.streaming??true,...(input.protocol==='codex-cli'?{subscription:true}:{})}}}
  async #profiles():Promise<ModelProfile[]>{try{return JSON.parse(await readFile(this.#profilesFile,'utf8')) as ModelProfile[]}catch{return[]}}
  async #secrets():Promise<Secrets>{try{return JSON.parse(await readFile(this.#secretsFile,'utf8')) as Secrets}catch{return{}}}
  async #state():Promise<{defaultBrainId?:string}>{try{return JSON.parse(await readFile(this.#stateFile,'utf8')) as {defaultBrainId?:string}}catch{return{}}}
  async #write(file:string,value:unknown){await mkdir(this.#root,{recursive:true});await writeFile(file,JSON.stringify(value,null,2),'utf8')}
}
