import { createHash, randomUUID } from 'node:crypto'; import type { EventBus } from '../../events/src/index.ts'; import type { JsonObject, ToolRisk, ToolSpec } from '../../protocol/src/index.ts'; import type { ApprovalController, ApprovalGrant } from './index.ts'
export type ApprovalMode='ask'|'risk'|'full'; export type ApprovalDecision='approve'|'reject'; export interface ApprovalRequestRecord{id:string;runId:string;kind:'tool';subject:string;tool:string;risk:ToolRisk;summary:string;requestHash:string;state:'pending'|'approved'|'rejected';createdAt:number;decidedAt?:number;decidedBy?:string}
type Pending={record:ApprovalRequestRecord;resolve(value:ApprovalGrant):void}
function redact(value:unknown):unknown{if(Array.isArray(value))return value.map(redact);if(!value||typeof value!=='object')return value;const out:Record<string,unknown>={};for(const[k,v]of Object.entries(value as Record<string,unknown>))out[k]=/token|secret|password|api.?key|authorization|credential/i.test(k)?'***':redact(v);return out}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(',')}}`;return JSON.stringify(value)}
function hash(runId:string,spec:ToolSpec,args:JsonObject){return createHash('sha256').update(`${runId}\n${spec.name}\n${stable(redact(args))}`).digest('hex')}
function needs(mode:ApprovalMode,spec:ToolSpec){if(spec.risk==='read')return false;if(spec.confirm==='always')return true;if(mode==='full')return false;if(mode==='ask')return true;return spec.risk==='modify'||spec.risk==='destructive'||spec.risk==='system'}
export class InteractiveApprovalController implements ApprovalController{
 #mode:ApprovalMode;#events:EventBus;#pending=new Map<string,Pending>();#updatedAt=Date.now();#updatedBy='';constructor(events:EventBus,mode:ApprovalMode='ask'){this.#events=events;this.#mode=mode}
 state(){return{mode:this.#mode,modeLabel:this.#mode==='ask'?'每次询问':this.#mode==='risk'?'仅高风险询问':'完全授权',updatedAt:this.#updatedAt,...(this.#updatedBy?{updatedBy:this.#updatedBy}:{}),pendingCount:this.#pending.size}}
 setMode(mode:ApprovalMode,by=''){this.#mode=mode;this.#updatedAt=Date.now();this.#updatedBy=by;return this.state()}
 pending(){return[...this.#pending.values()].map(p=>structuredClone(p.record)).sort((a,b)=>a.createdAt-b.createdAt)}
 async approve(spec:ToolSpec,args:JsonObject,runId:string,signal:AbortSignal):Promise<ApprovalGrant>{const requestHash=hash(runId,spec,args);if(!needs(this.#mode,spec))return{approved:true,requestHash};if(signal.aborted)return{approved:false,requestHash};const id=`approval_${randomUUID()}`;const safe=stable(redact(args));const record:ApprovalRequestRecord={id,runId,kind:'tool',subject:spec.name,tool:spec.name,risk:spec.risk,summary:`${spec.name} ${safe.length>600?safe.slice(0,600)+'…':safe}`,requestHash,state:'pending',createdAt:Date.now()};return new Promise(resolve=>{this.#pending.set(id,{record,resolve});this.#events.emit(runId,'approval-required',`${spec.name} requires approval`,{approvalId:id,tool:spec.name,risk:spec.risk,summary:record.summary,requestHash});signal.addEventListener('abort',()=>{const item=this.#pending.get(id);if(!item)return;this.#pending.delete(id);item.record.state='rejected';item.resolve({approved:false,requestHash});this.#events.emit(runId,'approval-resolved',`${spec.name}: cancelled`,{approvalId:id,decision:'reject'})},{once:true})})}
 resolve(id:string,decision:ApprovalDecision,by:string){const item=this.#pending.get(id);if(!item)throw new Error('审批请求不存在或已经处理');this.#pending.delete(id);item.record.state=decision==='approve'?'approved':'rejected';item.record.decidedAt=Date.now();item.record.decidedBy=by;item.resolve({approved:decision==='approve',requestHash:item.record.requestHash});this.#events.emit(item.record.runId,'approval-resolved',`${item.record.tool}: ${decision}`,{approvalId:id,decision,tool:item.record.tool});return structuredClone(item.record)}
}
