import type { JsonObject, NativeCapabilityLease, ToolSpec } from '../../protocol/src/index.ts'; import type { Tool, ToolContext } from './index.ts'
export interface NativeToolBridge{call<T=unknown>(method:string,params?:unknown,timeoutMs?:number):Promise<T>}
function req(args:JsonObject,key:string){const v=args[key];if(typeof v!=='string'||!v.trim())throw new Error(`${key} must be a non-empty string`);return v.trim()}
function num(args:JsonObject,key:string,fallback:number,min:number,max:number){const raw=args[key];if(raw===undefined||raw===null||raw==='')return fallback;const n=Number(raw);if(!Number.isFinite(n))throw new Error(`${key} must be a number`);return Math.max(min,Math.min(max,Math.floor(n)))}
export async function issueNativeCapability(bridge:NativeToolBridge,context:ToolContext,tool:ToolSpec,scope:string,payload:JsonObject){const approvalHash=context.authorization?.requestHash;if(!approvalHash)throw new Error(`native capability requires approval for ${tool.name}`);const lease=await bridge.call<NativeCapabilityLease>('capability/issue',{runId:context.runId,tool:tool.name,approvalHash,scope,payload,ttlMs:30000});if(!lease?.id||lease.scope!==scope||lease.runId!==context.runId||lease.tool!==tool.name)throw new Error('invalid Native Capability Lease');return lease}
abstract class NativeRead implements Tool{abstract readonly spec:ToolSpec;constructor(protected readonly bridge:NativeToolBridge){}abstract execute(a:JsonObject,c:ToolContext):Promise<{content:string;data?:unknown}>}
class RuntimeInspect extends NativeRead{readonly spec={name:'system.runtime.inspect',description:'Inspect the Rust Native Runtime and its native execution capabilities.',risk:'read',source:'native',inputSchema:{type:'object',properties:{},additionalProperties:false}} as const;async execute(){const data=await this.bridge.call<any>('runtime/status',{});return{content:`Native Runtime ${data.version??''}; ready=${data.ready??false}; capabilities=${(data.capabilities??[]).join(', ')}`,data}}}
class JavaInspect extends NativeRead{readonly spec={name:'system.java.inspect',description:'Inspect system and AGMP managed Java runtimes; returns actual java -version facts instead of model memory.',risk:'read',source:'native',inputSchema:{type:'object',properties:{},additionalProperties:false}} as const;async execute(){const data=await this.bridge.call<any>('environment/javaInspect',{});return{content:data.available?`Java ${data.version} major ${data.major}; executable=${data.executable}; source=${data.source}`:`No compatible Java detected: ${data.error??''}`,data}}}
class PortAvailable extends NativeRead{readonly spec={name:'network.port_available',description:'Deterministically test whether a local TCP port can be bound before deployment.',risk:'read',source:'native',inputSchema:{type:'object',properties:{port:{type:'integer',minimum:1025,maximum:65535}},required:['port'],additionalProperties:false}} as const;async execute(a:JsonObject){const port=num(a,'port',25565,1025,65535);const data=await this.bridge.call<any>('network/portAvailable',{host:'127.0.0.1',port});return{content:`127.0.0.1:${port} ${data.available?'is available':'is occupied'}`,data}}}
class ListFiles extends NativeRead{readonly spec={name:'filesystem.list',description:'List files inside AGMP workspace. Rust confines paths to the workspace.',risk:'read',source:'native',inputSchema:{type:'object',properties:{path:{type:'string'}},additionalProperties:false}} as const;async execute(a:JsonObject){const p=typeof a.path==='string'&&a.path.trim()?a.path.trim():'.';const data=await this.bridge.call<any[]>('fs/list',{path:p});return{content:data.slice(0,200).map(e=>`${e.directory?'[dir]':'[file]'} ${e.name}`).join('\n')||'(empty directory)',data}}}
class ReadText extends NativeRead{readonly spec={name:'filesystem.read_text',description:'Read a UTF-8 text file from AGMP workspace with bounded output.',risk:'read',source:'native',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path'],additionalProperties:false}} as const;async execute(a:JsonObject){const p=req(a,'path');const data=await this.bridge.call<any>('fs/readText',{path:p});const full=String(data.content??'');const content=full.length>32768?`${full.slice(0,32768)}\n[AGMP truncated]`:full;return{content,data:{path:p,chars:full.length,truncated:full.length>32768}}}}
class CreateDir implements Tool{readonly spec={name:'filesystem.create_directory',description:'Create a directory in the managed workspace behind Approval and a single-use Rust Capability Lease.',risk:'modify',source:'native',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path'],additionalProperties:false}} as const;constructor(private readonly bridge:NativeToolBridge){}async execute(a:JsonObject,c:ToolContext){const path=req(a,'path');const payload={path};const lease=await issueNativeCapability(this.bridge,c,this.spec,'filesystem.mkdir:workspace',payload);await this.bridge.call('fs/createDir',{...payload,capabilityLeaseId:lease.id,capabilityScope:lease.scope,runId:c.runId,tool:this.spec.name});return{content:`Created ${path}`}}}
class WriteText implements Tool{readonly spec={name:'filesystem.write_text',description:'Write UTF-8 text inside managed workspace. Exact path/content are bound to one-use Rust capability.',risk:'modify',source:'native',inputSchema:{type:'object',properties:{path:{type:'string'},content:{type:'string'}},required:['path','content'],additionalProperties:false}} as const;constructor(private readonly bridge:NativeToolBridge){}async execute(a:JsonObject,c:ToolContext){const path=req(a,'path');if(typeof a.content!=='string')throw new Error('content must be string');if(a.content.length>1048576)throw new Error('text write exceeds 1 MiB');const payload={path,content:a.content};const lease=await issueNativeCapability(this.bridge,c,this.spec,'filesystem.write:workspace',payload);await this.bridge.call('fs/writeText',{...payload,capabilityLeaseId:lease.id,capabilityScope:lease.scope,runId:c.runId,tool:this.spec.name});return{content:`Wrote ${a.content.length} chars to ${path}`}}}
class ProcessStart implements Tool{readonly spec={name:'process.start',description:'Start a non-interactive process whose cwd is confined to AGMP workspace. Exact command is approval/capability bound.',risk:'operate',source:'native',inputSchema:{type:'object',properties:{executable:{type:'string'},arguments:{type:'array',items:{type:'string'}},cwd:{type:'string'},maxOutputBytes:{type:'integer'}},required:['executable'],additionalProperties:false}} as const;constructor(private readonly bridge:NativeToolBridge){}async execute(a:JsonObject,c:ToolContext){const executable=req(a,'executable');const args=Array.isArray(a.arguments)?a.arguments.filter((v):v is string=>typeof v==='string'):[];const cwd=typeof a.cwd==='string'&&a.cwd.trim()?a.cwd.trim():null;const maxOutputBytes=num(a,'maxOutputBytes',1048576,1024,4194304);const payload={sessionId:null,executable,arguments:args,cwd,maxOutputBytes};const lease=await issueNativeCapability(this.bridge,c,this.spec,'process.start:workspace',payload as unknown as JsonObject);const data=await this.bridge.call<any>('jobs/start',{...payload,capabilityLeaseId:lease.id,capabilityScope:lease.scope,runId:c.runId,tool:this.spec.name});return{content:`Started job ${data.id??''}; pid=${data.pid??''}`,data}}}
class ProcessStatus extends NativeRead{readonly spec={name:'process.status',description:'Read Native job state.',risk:'read',source:'native',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false}} as const;async execute(a:JsonObject){const id=req(a,'id');const data=await this.bridge.call<any>('jobs/get',{id});return{content:`Job ${id}: ${data.state??''}; pid=${data.pid??''}; exit=${data.exitCode??''}`,data}}}
class ProcessOutput extends NativeRead{readonly spec={name:'process.output',description:'Read bounded Native job stdout/stderr.',risk:'read',source:'native',inputSchema:{type:'object',properties:{id:{type:'string'},after:{type:'integer'},limit:{type:'integer'}},required:['id'],additionalProperties:false}} as const;async execute(a:JsonObject){const id=req(a,'id');const data=await this.bridge.call<any>('jobs/output',{id,after:num(a,'after',0,0,Number.MAX_SAFE_INTEGER),limit:num(a,'limit',200,1,500)});const content=(data.chunks??[]).map((x:any)=>`[${x.stream??'out'}] ${x.text??''}`).join('');return{content:content.slice(0,32768)||'(no output)',data}}}
export function createNativeTools(bridge:NativeToolBridge):Tool[]{return[new RuntimeInspect(bridge),new JavaInspect(bridge),new PortAvailable(bridge),new ListFiles(bridge),new ReadText(bridge),new ProcessStatus(bridge),new ProcessOutput(bridge),new CreateDir(bridge),new WriteText(bridge),new ProcessStart(bridge)]}
